// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG2xfU-Cv93OzarXp1UNBaTCcWdSn7S5U',
    appId: '1:745251515679:web:11ba9e6d94b8cd09e9d42a',
    messagingSenderId: '745251515679',
    projectId: 'di-doctorapp',
    authDomain: 'di-doctorapp.firebaseapp.com',
    storageBucket: 'di-doctorapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7mxjGRfht_Rl392UyInIEaxi0KC3xeAc',
    appId: '1:745251515679:android:b485b0605feccd5de9d42a',
    messagingSenderId: '745251515679',
    projectId: 'di-doctorapp',
    storageBucket: 'di-doctorapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgZL4Mq10pNTjFBWyiDsMQ-M5gC_mWYf4',
    appId: '1:745251515679:ios:e04ebd674a26d44ce9d42a',
    messagingSenderId: '745251515679',
    projectId: 'di-doctorapp',
    storageBucket: 'di-doctorapp.firebasestorage.app',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgZL4Mq10pNTjFBWyiDsMQ-M5gC_mWYf4',
    appId: '1:745251515679:ios:e04ebd674a26d44ce9d42a',
    messagingSenderId: '745251515679',
    projectId: 'di-doctorapp',
    storageBucket: 'di-doctorapp.firebasestorage.app',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG2xfU-Cv93OzarXp1UNBaTCcWdSn7S5U',
    appId: '1:745251515679:web:b22a505b562f8b20e9d42a',
    messagingSenderId: '745251515679',
    projectId: 'di-doctorapp',
    authDomain: 'di-doctorapp.firebaseapp.com',
    storageBucket: 'di-doctorapp.firebasestorage.app',
  );
}
