// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqiTxuPD1J_C0jieXgpZGbEtXQKXeWIi0',
    appId: '1:916072699968:web:62fbaffc5aa962f887a7a5',
    messagingSenderId: '916072699968',
    projectId: 'dermatics-india-doctor',
    authDomain: 'dermatics-india-doctor.firebaseapp.com',
    storageBucket: 'dermatics-india-doctor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDft5QA1SdsbtNH84UFZjMIPr0nHGLjg0g',
    appId: '1:916072699968:android:8a7d20ef87e52ec387a7a5',
    messagingSenderId: '916072699968',
    projectId: 'dermatics-india-doctor',
    storageBucket: 'dermatics-india-doctor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDllEApuSVV4v2Vu7Fb6XL_sEuOi0bkueQ',
    appId: '1:916072699968:ios:b15a9bcd62c8ddd887a7a5',
    messagingSenderId: '916072699968',
    projectId: 'dermatics-india-doctor',
    storageBucket: 'dermatics-india-doctor.firebasestorage.app',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDllEApuSVV4v2Vu7Fb6XL_sEuOi0bkueQ',
    appId: '1:916072699968:ios:b15a9bcd62c8ddd887a7a5',
    messagingSenderId: '916072699968',
    projectId: 'dermatics-india-doctor',
    storageBucket: 'dermatics-india-doctor.firebasestorage.app',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqiTxuPD1J_C0jieXgpZGbEtXQKXeWIi0',
    appId: '1:916072699968:web:96a2712b06143cf287a7a5',
    messagingSenderId: '916072699968',
    projectId: 'dermatics-india-doctor',
    authDomain: 'dermatics-india-doctor.firebaseapp.com',
    storageBucket: 'dermatics-india-doctor.firebasestorage.app',
  );

}